go.property('infra_type', hash(""))

function init(self)
    if self.type == hash("") then
        error('no infra type specified')
    end
    timer.delay(0.1, false, function()
        msg.post(
            go.get_parent() --[[@as url]]
            , 'infra_added', {
                go_id = go.get_id(),
                infra_type = self.infra_type
            })
    end)
end

function final(self)
end

function on_message(self, message_id, message, sender)
end
