components {
  id: "infra"
  component: "/main/entities/infra/infra.script"
  properties {
    id: "infra_type"
    value: "helipad"
    type: PROPERTY_TYPE_HASH
  }
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"building-helipad\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/entities/infra/helipad/helipad.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"helipad\"\n"
  "mask: \"person\"\n"
  "mask: \"copter\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -90.0\n"
  "      y: 22.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.38268343\n"
  "      w: 0.9238795\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"stairs\"\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 44.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "    id: \"pad\"\n"
  "  }\n"
  "  data: 36.0\n"
  "  data: 1.0\n"
  "  data: 10.0\n"
  "  data: 65.0\n"
  "  data: 4.0\n"
  "  data: 10.0\n"
  "}\n"
  "locked_rotation: true\n"
  ""
}
