local dd = require 'helpers.debug_draw'

function init(self)
	self.hovering_gos = {}
	msg.post('.', 'acquire_input_focus')
end

function late_update(self, dt)
	dd.draw_cross(go.get_position(), 5, { z = 0 })
end

function on_message(self, message_id, message, sender)
	if message_id == hash('trigger_response') then
		if message.enter then
			self.hovering_gos[message.other_id] = message.other_id
		else
			self.hovering_gos[message.other_id] = nil
		end
	end
end

function on_input(self, action_id, action)
	if action.screen_x and action.screen_y then
		local world_touch_pos = camera.screen_xy_to_world(action.screen_x, action.screen_y, camera.get_cameras()[1])
		go.set_position(world_touch_pos)
	end

	if action_id == hash('touch') and action.pressed then
		for k, v in pairs(self.hovering_gos) do
			if v ~= nil and go.exists(v) then
				msg.post(v, 'cursor_click')
				return true
			else
				self.hovering_gos[k] = nil
			end
		end
	end
end
