local building_registry = require "main.systems.buildings.registry"

function init(self)
    self.building_id = building_registry.register(go.get_id())
end

function final(self)
    building_registry.remove(self.building_id)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("add-infra") then
        building_registry.add_infra(self.building_id, message)
    end
end
